### PR TITLE
Removes AI/cleverbot handler

### PR DESCRIPTION
**Pull request by matt-bernhardt**
Hey @JPrevost - just to make sure I understand how lita would work, this is how we'd disable the cleverbot integration?

And, it looks like this layer of Lita is just an integration for various plugins, right? At least so far?

To be clear, I'm not asking for this to be merged right now - just trying to understand how the bot is built.

### CODE REVIEW

**Comment by JPrevost** [comment]
You'd also want to run `bundle install` which will update the `Gemfile.lock` to remove the dependencies.

And yeah, this is all just the main Lita gem with some additional gems (dependencies) and some minor config.

**Comment by matt-bernhardt** [comment]
Ah, this is where me being on Windows trips me up.

```
$ bundle install
Your Ruby version is 2.2.4, but your Gemfile specified 2.3.0
```

**Comment by JPrevost** [comment]
To run this locally there are two dependencies.
- ruby 2.3.0 (technically you could just change that in the Gemfile to whatever you've got)
- redis

**Comment by JPrevost** [comment]
They supply a vagrant script to get you started if you don't have those dependencies.

https://docs.lita.io/getting-started/installation/

**Comment by matt-bernhardt** [comment]
Closing / deleting this branch as part of a general cleanup.

**Pull request closed without merging**
